{
 "title": "Kubearmor Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Number of logs on given Host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kubearmor_alerts_in_host_total) by (HostName)"
    }
   ]
  },
  {
   "title": "Number of logs on given Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kubearmor_alerts_in_pod_total) by (PodName)"
    }
   ]
  },
  {
   "title": "Number of logs in given Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kubearmor_alerts_in_namespace_total) by (NamespaceName)"
    }
   ]
  },
  {
   "title": "Number of logs on given Container ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kubearmor_alerts_in_container_total) by (ContainerName)"
    }
   ]
  },
  {
   "title": "Number of logs with given Policy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kubearmor_alerts_with_policy_total) by (PolicyName)"
    }
   ]
  },
  {
   "title": "Number of logs with given Severity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kubearmor_alerts_with_severity_total) by (Severity)"
    }
   ]
  },
  {
   "title": "Number of logs with given Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kubearmor_alerts_with_type_total) by (Type)"
    }
   ]
  },
  {
   "title": "Number of logs with given Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kubearmor_alerts_with_operation_total) by (Operation)"
    }
   ]
  },
  {
   "title": "Number of logs with given Action",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kubearmor_alerts_with_action_total) by (Action)"
    }
   ]
  }
 ]
}